using System;
using System.Collections.Generic;
using System.Linq;
using Service;
using UnityEngine;
namespace ExpandWorldData;

using Operation = Action<int, float>;
public class TerrainNode
{
  public int Index;
  public float Distance;
}

public partial class Terrain
{
  public static Dictionary<string, Color> Paints = new() {
    {"grass", Color.black},
    {"patches", new(0f, 0.75f, 0f)},
    {"grass_dark", new(0.6f, 0.5f, 0f)},
    {"dirt", Color.red},
    {"cultivated", Color.green},
    {"paved", Color.blue},
    {"paved_moss", new(0f, 0f, 0.5f)},
    {"paved_dirt", new(1f, 0f, 0.5f)},
    {"paved_dark", new(0f, 1f, 0.5f)},
  };
  public static Color ParsePaint(string paint)
  {
    return ParsePaintColor(paint);
  }
  private static Color ParsePaintColor(string paint)
  {
    var split = Parse.Split(paint);
    if (split.Length < 3 && Paints.TryGetValue(paint, out var color)) return color;
    return new(Parse.Float(split, 0), Parse.Float(split, 1), Parse.Float(split, 2), Parse.Float(split, 3, 1f));
  }
  private static float CalculateSmooth(float smooth, float distance) => (1f - distance) >= smooth ? 1f : (1f - distance) / smooth;

  private static void GetHeightNodes(List<TerrainNode> nodes, Heightmap hm, Vector3 centerPos, float radius)
  {
    if (radius == 0f) return;
    var max = hm.m_width + 1;
    // Never return edges as they overlap with other zones.
    for (int x = 1; x < max - 1; x++)
    {
      for (int z = 1; z < max - 1; z++)
      {
        var nodePos = VertexToWorld(hm, x, z);
        var distance = Utils.DistanceXZ(centerPos, nodePos);
        if (distance > radius) continue;
        nodes.Add(new()
        {
          Index = z * max + x,
          Distance = distance / radius
        });
      }
    }
  }
  private static void GetPaintNodes(List<TerrainNode> nodes, Heightmap hm, Vector3 centerPos, float radius)
  {
    var max = hm.m_width;
    for (int x = 0; x < max; x++)
    {
      for (int z = 0; z < max; z++)
      {
        var nodePos = VertexToWorld(hm, x, z);
        // Painting is applied from the corner of the node, not the center.
        nodePos.x += 0.5f;
        nodePos.z += 0.5f;
        var distance = Utils.DistanceXZ(centerPos, nodePos);
        if (distance > radius) continue;
        nodes.Add(new()
        {
          Index = z * max + x,
          Distance = distance / radius
        });
      }
    }
  }

  private static Vector3 VertexToWorld(Heightmap hmap, int x, int y)
  {
    var vector = hmap.transform.position;
    vector.x += (x - hmap.m_width / 2 + 0.5f) * hmap.m_scale;
    vector.z += (y - hmap.m_width / 2 + 0.5f) * hmap.m_scale;
    return vector;
  }
  private static readonly int TerrainHash = "_TerrainCompiler".GetStableHashCode();
  public static void ChangeTerrain(Vector3 pos, Action<Heightmap, TerrainFakeData> action)
  {
    var hm = Heightmap.FindHeightmap(pos);
    if (hm == null) return;
    var compiler = FindCompiler(hm, pos);
    if (compiler == null) return;
    TerrainFakeData data = new(hm, compiler);
    action(hm, data);
    data.Save();
    var tc = TerrainComp.FindTerrainCompiler(pos);
    if (tc)
      tc.Load();
    else
      Log.Warning($"TerrainCompiler not found at zone {ZoneSystem.GetZone(pos)}. Usually caused by heightmap being regenerated by a manual reset operation");
    hm.Poke(false);
  }

  public static void ApplyBlueprint(Blueprint blueprint, Vector3 position, Quaternion rotation, ZoneSystem.SpawnMode mode, List<GameObject> spawnedGhostObjects)
  {
    if (!Helper.IsServer()) return;
    var isGhost = mode == ZoneSystem.SpawnMode.Ghost;
    try
    {
      ApplyBlueprintSnapshot(blueprint, position, rotation, isGhost, spawnedGhostObjects);
    }
    catch (Exception e)
    {
      // Location generation must keep unwinding normally so vanilla can clean
      // its temporary zone root and spawned ghost objects.
      Log.Warning($"Blueprint {blueprint.Name}: Terrain snapshot was not applied completely: {e.Message}");
    }
  }

  public static void FinalizeGhostTerrain(Vector3 position, List<GameObject> spawnedGhostObjects, string context)
  {
    if (IsValidZonePosition(position, 0f))
      DetachCurrentGhostCompiler(position, spawnedGhostObjects, context);
  }

  // SpawnZone calls PlaceLocations and PlaceVegetation synchronously, before
  // ZNetScene gets a chance to instantiate a compiler ZDO that was written by
  // a snapshot in another zone. Attach it here so both operations see the
  // canonical terrain. Ghost instances are detached into vanilla's cleanup
  // list because their Heightmap belongs to the temporary zone root.
  public static void PrepareZoneTerrain(Heightmap heightmap, ZoneSystem.SpawnMode mode, List<GameObject> spawnedObjects)
  {
    if (!Helper.IsServer() || mode == ZoneSystem.SpawnMode.Client || !heightmap || heightmap.IsDistantLod) return;
    var center = heightmap.transform.position;
    if (!IsValidZonePosition(center, 0f))
    {
      Log.Warning("Terrain snapshot preload skipped a Heightmap with invalid world coordinates.");
      return;
    }

    var scene = ZNetScene.instance;
    var currentZone = ZoneSystem.GetZone(center);
    TerrainComp? compiler = null;
    GameObject? createdCompilerObject = null;
    try
    {
      if (!scene)
        throw new InvalidOperationException("ZNetScene is not available.");
      var zdo = FindSingleCompiler(currentZone);
      if (zdo == null || zdo.GetByteArray(ZDOVars.s_TCData) == null) return;

      var instance = scene.FindInstance(zdo);
      if (instance)
        compiler = instance.GetComponent<TerrainComp>();
      else
      {
        compiler = TerrainComp.FindTerrainCompiler(center);
        if (!compiler)
        {
          createdCompilerObject = scene.CreateObject(zdo);
          compiler = createdCompilerObject?.GetComponent<TerrainComp>();
        }
      }

      ValidateLoadedCompiler(scene, zdo, compiler, heightmap, center);
      if (!compiler!.Load())
        throw new InvalidOperationException($"TerrainCompiler data could not be loaded at zone {currentZone}.");
      if (mode == ZoneSystem.SpawnMode.Ghost)
        DetachGhostCompiler(scene, zdo, compiler, heightmap, currentZone, spawnedObjects);
      heightmap.Poke(false);
    }
    catch (Exception e)
    {
      var currentGhostCompiler = mode == ZoneSystem.SpawnMode.Ghost && compiler &&
        ReferenceEquals(compiler.m_hmap, heightmap) && ZoneSystem.GetZone(compiler.m_hmap.transform.position) == currentZone;
      if (createdCompilerObject || currentGhostCompiler)
        CleanupCompilerInstance(scene, compiler, spawnedObjects, createdCompilerObject);
      Log.Warning($"Terrain snapshot could not be prepared before zone contents at {currentZone}: {e.Message}");
    }
  }

  private static void ApplyBlueprintSnapshot(Blueprint blueprint, Vector3 position, Quaternion rotation, bool isGhost, List<GameObject> spawnedGhostObjects)
  {
    if (!IsValidZonePosition(position, 0f) || !IsFinite(rotation) || QuaternionMagnitudeSquared(rotation) <= 0.0001f)
      throw new InvalidOperationException("Terrain snapshot placement contains an invalid position or rotation.");
    var hasHeight = blueprint.TerrainHeight?.HasValues == true;
    var hasPaint = blueprint.TerrainPaint?.HasValues == true;
    if (!hasHeight && !hasPaint) return;
    if (hasHeight && (!IsValidTerrainTransform(blueprint.TerrainHeight!) || !blueprint.TerrainHeight!.AllValues(IsFinite)) ||
        hasPaint && (!IsValidTerrainTransform(blueprint.TerrainPaint!) || !blueprint.TerrainPaint!.AllValues(IsFinite)))
      throw new InvalidOperationException("Terrain snapshot reference contains invalid transformed values.");
    var radius = Mathf.Max(blueprint.TerrainHeight?.GetRadius() ?? 0f, blueprint.TerrainPaint?.GetRadius() ?? 0f);
    if (!IsFinite(radius) || radius < 0f)
      throw new InvalidOperationException("Terrain snapshot radius is invalid.");

    var template = FindLoadedHeightmap(position) ?? ZoneSystem.instance?.m_zonePrefab?.GetComponentInChildren<Heightmap>();
    if (!template || template.IsDistantLod || template.m_width <= 0 || !IsFinite(template.m_scale) || template.m_scale <= 0f ||
        HeightmapBuilder.instance == null || WorldGenerator.instance == null)
    {
      Log.Warning($"Blueprint {blueprint.Name}: Terrain template is not ready for the terrain snapshot.");
      return;
    }
    var scene = ZNetScene.instance;
    var templateView = template.m_terrainCompilerPrefab?.GetComponent<ZNetView>();
    var registeredCompiler = scene ? scene.GetPrefab(TerrainHash) : null;
    if (!scene || !templateView || !registeredCompiler || !registeredCompiler.GetComponent<TerrainComp>())
    {
      Log.Warning($"Blueprint {blueprint.Name}: Terrain compiler prefab is not ready for the terrain snapshot.");
      return;
    }

    var heightMargin = hasHeight ? Mathf.Max(0.001f, blueprint.TerrainHeight!.DistanceBetweenNodes) : 0f;
    var paintMargin = hasPaint ? Mathf.Max(0.001f, blueprint.TerrainPaint!.DistanceBetweenNodes) : 0f;
    var applicationRadius = radius + Mathf.Max(template.m_scale, heightMargin, paintMargin);
    if (!IsFinite(applicationRadius) || applicationRadius <= 0f)
      throw new InvalidOperationException("Terrain snapshot application radius is invalid.");
    var minPosition = position - new Vector3(applicationRadius, 0f, applicationRadius);
    var maxPosition = position + new Vector3(applicationRadius, 0f, applicationRadius);
    if (!IsFinite(minPosition) || !IsFinite(maxPosition) || !IsValidZonePosition(position, applicationRadius))
      throw new InvalidOperationException("Terrain snapshot bounds are invalid.");
    var minZone = ZoneSystem.GetZone(minPosition);
    var maxZone = ZoneSystem.GetZone(maxPosition);
    var spanX = (long)maxZone.x - minZone.x + 1L;
    var spanZ = (long)maxZone.y - minZone.y + 1L;
    var zoneCount = spanX > 0L && spanZ > 0L && spanX <= 64L && spanZ <= 64L ? spanX * spanZ : long.MaxValue;
    if (zoneCount <= 0 || zoneCount > 64)
    {
      Log.Warning($"Blueprint {blueprint.Name}: Terrain snapshot covers an unsupported number of zones ({zoneCount}).");
      return;
    }

    var width = template.m_width;
    var scale = template.m_scale;
    var max = width + 1;
    var count = max * max;
    var ghostZone = ZoneSystem.GetZone(position);
    List<(Vector3 Center, Heightmap? Heightmap, TerrainComp? Compiler, ZDO? Zdo, int Changes, byte[]? Payload)> staged = [];
    try
    {
      for (long zoneOffsetZ = 0; zoneOffsetZ < spanZ; ++zoneOffsetZ)
      {
        var zoneZ = (int)(minZone.y + zoneOffsetZ);
        for (long zoneOffsetX = 0; zoneOffsetX < spanX; ++zoneOffsetX)
        {
          var zoneX = (int)(minZone.x + zoneOffsetX);
          var zone = new Vector2i(zoneX, zoneZ);
          var center = ZoneSystem.GetZonePos(zone);
          var hasSnapshotValues = false;
          for (var z = 0; z < max && !hasSnapshotValues; ++z)
          {
            for (var x = 0; x < max; ++x)
            {
              var nodePosition = BlueprintVertexToWorld(center, width, scale, x, z);
              if (blueprint.TerrainHeight?.FindNearest(nodePosition, position, rotation).HasValue == true ||
                  blueprint.TerrainPaint?.FindNearest(nodePosition, position, rotation).HasValue == true)
              {
                hasSnapshotValues = true;
                break;
              }
            }
          }
          if (!hasSnapshotValues) continue;

          var buildData = HeightmapBuilder.instance.RequestTerrainSync(center, width, scale, template.IsDistantLod, WorldGenerator.instance);
          if (buildData?.m_baseHeights == null || buildData.m_baseHeights.Count != count)
            throw new InvalidOperationException($"Base terrain at zone {zone} is not ready.");
          if (buildData.m_baseHeights.Any(value => !IsFinite(value)))
            throw new InvalidOperationException($"Base terrain at zone {zone} contains invalid heights.");

          var zdo = FindSingleCompiler(zone);
          var data = new TerrainFakeData(width, zdo?.GetByteArray(ZDOVars.s_TCData), true);
          var changes = 0;
          for (var z = 0; z < max; ++z)
          {
            for (var x = 0; x < max; ++x)
            {
              var index = z * max + x;
              var nodePosition = BlueprintVertexToWorld(center, width, scale, x, z);
              var height = blueprint.TerrainHeight?.FindNearest(nodePosition, position, rotation);
              if (height.HasValue)
              {
                var targetLocalHeight = height.Value + position.y - center.y;
                var levelDelta = targetLocalHeight - buildData.m_baseHeights[index];
                if (!IsFinite(targetLocalHeight) || !IsFinite(levelDelta))
                  throw new InvalidOperationException($"Terrain height at zone {zone} is not finite.");
                if (data.SetHeight(index, levelDelta))
                  changes += 1;
              }
              var paint = blueprint.TerrainPaint?.FindNearest(nodePosition, position, rotation);
              if (paint.HasValue)
              {
                if (!IsFinite(paint.Value))
                  throw new InvalidOperationException($"Terrain paint at zone {zone} is not finite.");
                if (data.SetPaint(index, paint.Value))
                  changes += 1;
              }
            }
          }
          if (changes > 0 && zdo != null && zdo.HasOwner() && zdo.GetOwner() != ZDOMan.GetSessionID())
            throw new InvalidOperationException($"TerrainCompiler at zone {zone} is owned by an active peer.");

          byte[]? payload = null;
          if (changes > 0)
          {
            data.MarkOperation(position, applicationRadius);
            payload = data.Serialize();
          }

          var loadedHeightmap = FindLoadedHeightmap(center);
          var compiler = TerrainComp.FindTerrainCompiler(center);
          if (compiler)
          {
            if (!loadedHeightmap || !ReferenceEquals(compiler.m_hmap, loadedHeightmap))
              throw new InvalidOperationException($"Loaded TerrainCompiler at zone {zone} is attached to a different Heightmap.");
            var liveZdo = compiler.GetComponent<ZNetView>()?.GetZDO();
            if (zdo == null || !ReferenceEquals(liveZdo, zdo))
              throw new InvalidOperationException($"Loaded TerrainCompiler at zone {zone} does not match its sector ZDO.");
          }
          if (zdo != null)
          {
            var instance = scene.FindInstance(zdo);
            if (instance)
            {
              var instanceCompiler = instance.GetComponent<TerrainComp>();
              if (!instanceCompiler)
                throw new InvalidOperationException($"TerrainCompiler ZDO at zone {zone} is used by another prefab instance.");
              if (compiler && compiler != instanceCompiler)
                throw new InvalidOperationException($"TerrainCompiler ZDO at zone {zone} has multiple live instances.");
              compiler = instanceCompiler;
            }
          }
          if (compiler && loadedHeightmap)
            ValidateLoadedCompiler(scene, zdo!, compiler, loadedHeightmap, center, isGhost && zone == ghostZone);
          staged.Add((center, loadedHeightmap, compiler, zdo, changes, payload));
        }
      }
    }
    catch (Exception e)
    {
      // Nothing has been saved yet, so malformed or unavailable terrain cannot
      // leave only part of a multi-heightmap snapshot applied.
      Log.Warning($"Blueprint {blueprint.Name}: Terrain snapshot was not applied: {e.Message}");
      return;
    }

    // Commit every precomputed payload before refreshing any live Heightmap.
    // A bad live instance must not prevent later zones from receiving their
    // canonical snapshot data.
    try
    {
      for (var i = 0; i < staged.Count; ++i)
      {
        var item = staged[i];
        if (item.Changes <= 0) continue;
        var zdo = item.Zdo ?? CreateCompiler(item.Center, templateView);
        zdo.SetOwner(ZDOMan.GetSessionID());
        zdo.Set(ZDOVars.s_TCData, item.Payload!);
        staged[i] = (item.Center, item.Heightmap, item.Compiler, zdo, item.Changes, item.Payload);
      }
    }
    catch (Exception e)
    {
      Log.Warning($"Blueprint {blueprint.Name}: Terrain snapshot commit failed: {e.Message}");
      return;
    }

    var changedHeightmaps = staged.Count(item => item.Changes > 0);
    var changedNodes = staged.Sum(item => item.Changes);
    foreach (var item in staged)
    {
      var zdo = item.Zdo;
      if (zdo == null || !item.Heightmap || zdo.GetByteArray(ZDOVars.s_TCData) == null) continue;
      GameObject? createdCompilerObject = null;
      TerrainComp? compiler = item.Compiler;
      try
      {
        if (!compiler)
        {
          var instance = scene.FindInstance(zdo);
          if (instance)
            compiler = instance.GetComponent<TerrainComp>();
          else
          {
            var liveCompiler = TerrainComp.FindTerrainCompiler(item.Center);
            if (liveCompiler)
              compiler = liveCompiler;
            else
            {
              createdCompilerObject = scene.CreateObject(zdo);
              compiler = createdCompilerObject?.GetComponent<TerrainComp>();
            }
          }
        }

        var isCurrentGhostZone = isGhost && ZoneSystem.GetZone(item.Center) == ghostZone;
        ValidateLoadedCompiler(scene, zdo, compiler, item.Heightmap, item.Center, isCurrentGhostZone);
        if (!compiler!.Load())
          throw new InvalidOperationException($"TerrainCompiler data could not be loaded at zone {ZoneSystem.GetZone(item.Center)}.");
        if (isCurrentGhostZone)
        {
          if (IsDetachedGhostCompiler(scene, zdo, compiler))
          {
            if (!spawnedGhostObjects.Contains(compiler.gameObject))
              spawnedGhostObjects.Add(compiler.gameObject);
          }
          else
            DetachGhostCompiler(scene, zdo, compiler, item.Heightmap, ghostZone, spawnedGhostObjects);
        }
        item.Heightmap.Poke(false);
      }
      catch (Exception e)
      {
        var isCurrentGhostCompiler = isGhost && ZoneSystem.GetZone(item.Center) == ghostZone &&
          compiler && item.Heightmap && ReferenceEquals(compiler.m_hmap, item.Heightmap);
        if (createdCompilerObject || isCurrentGhostCompiler)
          CleanupCompilerInstance(scene, compiler, spawnedGhostObjects, createdCompilerObject);
        Log.Warning($"Blueprint {blueprint.Name}: Terrain snapshot at zone {ZoneSystem.GetZone(item.Center)} was saved but could not refresh its loaded Heightmap: {e.Message}");
      }
    }
    if (changedHeightmaps > 0)
    {
      ClutterSystem.instance?.ResetGrass(position, applicationRadius);
      Log.Debug($"Blueprint {blueprint.Name}: Applied terrain snapshot to {changedNodes} nodes on {changedHeightmaps} heightmaps.");
    }
  }

  private static Vector3 BlueprintVertexToWorld(Vector3 center, int width, float scale, int x, int z)
  {
    center.x += (x - width / 2) * scale;
    center.z += (z - width / 2) * scale;
    return center;
  }

  private static bool IsFinite(float value) => !float.IsNaN(value) && !float.IsInfinity(value);
  private static bool IsFinite(Vector3 value) => IsFinite(value.x) && IsFinite(value.y) && IsFinite(value.z);
  private static bool IsFinite(Quaternion value) => IsFinite(value.x) && IsFinite(value.y) && IsFinite(value.z) && IsFinite(value.w);
  private static bool IsFinite(Color value) => IsFinite(value.r) && IsFinite(value.g) && IsFinite(value.b) && IsFinite(value.a);
  private const double MaxZoneCoordinate = ((double)int.MaxValue - 1024d) * ZoneSystem.c_ZoneSize;
  private static bool IsValidZonePosition(Vector3 value, float margin) =>
    IsFinite(value) && IsFinite(margin) && margin >= 0f &&
    Math.Abs((double)value.x) <= MaxZoneCoordinate - margin &&
    Math.Abs((double)value.z) <= MaxZoneCoordinate - margin;
  private static float QuaternionMagnitudeSquared(Quaternion value) =>
    value.x * value.x + value.y * value.y + value.z * value.z + value.w * value.w;
  private static bool IsValidTerrainTransform<T>(BlueprintTerrain<T> terrain) where T : struct =>
    IsFinite(terrain.CenterPosition) && IsFinite(terrain.CenterRotation) &&
    IsFinite(QuaternionMagnitudeSquared(terrain.CenterRotation)) && QuaternionMagnitudeSquared(terrain.CenterRotation) > 0.0001f &&
    IsFinite(terrain.DistanceBetweenNodes) && terrain.DistanceBetweenNodes > 0f;

  private static Heightmap? FindLoadedHeightmap(Vector3 position)
  {
    List<Heightmap> heightmaps = [];
    Heightmap.FindHeightmap(position, 0f, heightmaps);
    return heightmaps.FirstOrDefault(heightmap => heightmap && !heightmap.IsDistantLod);
  }

  private static void ValidateLoadedCompiler(ZNetScene scene, ZDO zdo, TerrainComp? compiler, Heightmap heightmap, Vector3 position, bool allowDetachedGhost = false)
  {
    var zone = ZoneSystem.GetZone(position);
    if (!compiler || !ReferenceEquals(compiler.m_hmap, heightmap))
      throw new InvalidOperationException($"TerrainCompiler at zone {zone} is not attached to the expected Heightmap.");
    var view = compiler.m_nview;
    if (!view || !ReferenceEquals(view.GetZDO(), zdo))
      throw new InvalidOperationException($"TerrainCompiler at zone {zone} is not attached to its sector ZDO.");
    if (!ReferenceEquals(scene.FindInstance(zdo), view) &&
        !(allowDetachedGhost && IsDetachedGhostCompiler(scene, zdo, compiler)))
      throw new InvalidOperationException($"TerrainCompiler at zone {zone} is not the canonical scene instance.");
  }

  private static bool IsDetachedGhostCompiler(ZNetScene scene, ZDO zdo, TerrainComp compiler)
  {
    var view = compiler.m_nview;
    return view && ReferenceEquals(view.GetZDO(), zdo) && view.m_ghost && !zdo.Created && scene.FindInstance(zdo) == null;
  }

  private static void DetachGhostCompiler(ZNetScene scene, ZDO zdo, TerrainComp compiler, Heightmap heightmap, Vector2i ghostZone, List<GameObject> spawnedGhostObjects)
  {
    if (ZoneSystem.GetZone(heightmap.transform.position) != ghostZone)
      throw new InvalidOperationException($"TerrainCompiler at zone {ZoneSystem.GetZone(heightmap.transform.position)} is not part of the current ghost zone {ghostZone}.");
    ValidateLoadedCompiler(scene, zdo, compiler, heightmap, heightmap.transform.position);
    var view = compiler.m_nview;
    // Mirror EWD's ghost-init cleanup while keeping the ZDO bound long enough
    // for TerrainComp to affect this temporary Heightmap.
    view.m_ghost = true;
    zdo.Created = false;
    if (!scene.m_instances.Remove(zdo))
      throw new InvalidOperationException($"TerrainCompiler at zone {ZoneSystem.GetZone(heightmap.transform.position)} could not be detached from the scene.");
    if (!spawnedGhostObjects.Contains(compiler.gameObject))
      spawnedGhostObjects.Add(compiler.gameObject);
  }

  private static void DetachCurrentGhostCompiler(Vector3 position, List<GameObject> spawnedGhostObjects, string blueprintName)
  {
    var heightmap = FindLoadedHeightmap(position);
    var compiler = TerrainComp.FindTerrainCompiler(position);
    var ghostZone = ZoneSystem.GetZone(position);
    if (!heightmap || ZoneSystem.GetZone(heightmap.transform.position) != ghostZone ||
        !compiler || !ReferenceEquals(compiler.m_hmap, heightmap)) return;
    var view = compiler.m_nview;
    if (!view)
    {
      CleanupCompilerInstance(ZNetScene.instance, compiler, spawnedGhostObjects);
      Log.Warning($"Blueprint {blueprintName}: Temporary TerrainCompiler had no ZNetView and was discarded.");
      return;
    }
    var zdo = view.GetZDO();
    if (zdo == null)
    {
      CleanupCompilerInstance(ZNetScene.instance, compiler, spawnedGhostObjects);
      Log.Warning($"Blueprint {blueprintName}: Temporary TerrainCompiler had no ZDO and was discarded.");
      return;
    }

    var scene = ZNetScene.instance;
    try
    {
      // A compiler detached by the snapshot commit remains usable until
      // vanilla destroys every object in spawnedGhostObjects.
      if (view.m_ghost && !zdo.Created && scene && scene.FindInstance(zdo) == null)
      {
        if (!spawnedGhostObjects.Contains(compiler.gameObject))
          spawnedGhostObjects.Add(compiler.gameObject);
        return;
      }
      if (!scene)
        throw new InvalidOperationException("ZNetScene is not available.");
      DetachGhostCompiler(scene, zdo, compiler, heightmap, ghostZone, spawnedGhostObjects);
    }
    catch (Exception e)
    {
      CleanupCompilerInstance(scene, compiler, spawnedGhostObjects);
      Log.Warning($"Blueprint {blueprintName}: Temporary TerrainCompiler was discarded after ghost cleanup failed: {e.Message}");
    }
  }

  private static void CleanupCompilerInstance(ZNetScene? scene, TerrainComp? compiler, List<GameObject> spawnedGhostObjects, GameObject? fallbackObject = null)
  {
    try
    {
      var obj = compiler ? compiler.gameObject : fallbackObject;
      if (obj)
        spawnedGhostObjects.Remove(obj);
      var view = compiler ? compiler.m_nview : obj?.GetComponent<ZNetView>();
      if (view)
      {
        var zdo = view.GetZDO();
        if (zdo != null)
        {
          if (scene && ReferenceEquals(scene.FindInstance(zdo), view))
            scene.m_instances.Remove(zdo);
          view.ResetZDO();
        }
      }
      if (compiler)
        TerrainComp.s_instances.Remove(compiler);
      if (obj)
        UnityEngine.Object.Destroy(obj);
    }
    catch (Exception e)
    {
      Log.Warning($"Failed to clean up a temporary TerrainCompiler: {e.Message}");
    }
  }

  private static List<ZDO> FindCompilers(Vector2i zone)
  {
    List<ZDO> objects = [];
    ZDOMan.instance.FindObjects(zone, objects);
    return objects.Where(zdo => zdo.GetPrefab() == TerrainHash).ToList();
  }

  private static ZDO? FindSingleCompiler(Vector2i zone)
  {
    var compilers = FindCompilers(zone);
    if (compilers.Count > 1)
      throw new InvalidOperationException($"Zone {zone} contains {compilers.Count} TerrainCompiler ZDOs.");
    var compiler = compilers.FirstOrDefault();
    if (compiler != null && Utils.DistanceXZ(compiler.GetPosition(), ZoneSystem.GetZonePos(zone)) > 1f)
      throw new InvalidOperationException($"TerrainCompiler ZDO at zone {zone} is not near the expected zone center.");
    return compiler;
  }

  private static ZDO CreateCompiler(Vector3 position, ZNetView templateView)
  {
    var zdo = ZDOMan.instance.CreateNewZDO(position, TerrainHash);
    zdo.Persistent = templateView.m_persistent;
    zdo.Type = templateView.m_type;
    zdo.Distant = templateView.m_distant;
    zdo.SetPrefab(TerrainHash);
    zdo.SetRotation(Quaternion.identity);
    return zdo;
  }

  private static ZDO FindCompiler(Heightmap hm, Vector3 pos)
  {
    var zone = ZoneSystem.GetZone(pos);
    var tc = FindCompilers(zone).FirstOrDefault();
    if (tc == null)
      return hm.GetAndCreateTerrainCompiler().m_nview.GetZDO();
    return tc;
  }

  public static void Level(Heightmap hm, TerrainFakeData data, Vector3 pos, float radius, float border)
  {
    radius += border;
    if (radius == 0f) return;
    var smooth = border / radius;
    List<TerrainNode> nodes = [];
    GetHeightNodes(nodes, hm, pos, radius);
    void action(int index, float distance)
    {
      var multiplier = CalculateSmooth(smooth, distance);
      data.SetHeight(index, multiplier * (pos.y - hm.m_buildData.m_baseHeights[index]));
    }
    DoOperation(nodes, pos, radius, action);
  }
  public static void Paint(Heightmap hm, TerrainFakeData data, Vector3 pos, string paint, float radius, float border)
  {
    radius += border;
    if (radius == 0f) return;
    var smooth = border / radius;
    List<TerrainNode> nodes = [];
    Color color = ParsePaint(paint);
    GetPaintNodes(nodes, hm, pos, radius);
    void action(int index, float distance)
    {
      var multiplier = CalculateSmooth(smooth, distance);
      data.LerpColor(index, color, multiplier);
    }
    DoOperation(nodes, pos, radius, action);
  }

  private static void DoOperation(List<TerrainNode> nodes, Vector3 pos, float radius, Operation action)
  {
    foreach (var node in nodes)
      action(node.Index, node.Distance);
    ClutterSystem.instance?.ResetGrass(pos, radius);
  }
}

// TerrainCompiler is not loaded when Upgrade World resets locations.
// So using HeightMap.GetAndCreateTerrainCompiler would create a duplicate compiler.
// To avoid that, do operations directly on the ZDO data.
// This also ensures that default terrain state is used, so any previous operations won't affect the result.
public class TerrainFakeData
{
  public TerrainFakeData(Heightmap hm, ZDO zdo, bool fullPaintGrid = false)
    : this(hm.m_width, zdo.GetByteArray(ZDOVars.s_TCData), fullPaintGrid)
  {
    Zdo = zdo;
  }
  public TerrainFakeData(int width, byte[]? serializedData, bool fullPaintGrid = false)
  {
    if (width <= 0 || width > 2048)
      throw new InvalidOperationException($"Terrain width {width} is not supported.");
    var num = width + 1;
    ExpectedHeightCount = num * num;
    ExpectedLegacyPaintCount = width * width;
    ExpectedFullPaintCount = ExpectedHeightCount;
    HeightNodes = new HeightNode[num * num];
    PaintNodes = new Color[width * width];
    PaintModified = new bool[PaintNodes.Length];
    for (int i = 0; i < PaintNodes.Length; i++)
      PaintNodes[i] = Heightmap.m_paintMaskNothing;
    Load(serializedData);
    if (fullPaintGrid)
    {
      if (HeightNodes.Length != num * num)
        throw new InvalidOperationException($"Terrain height array length {HeightNodes.Length} is not supported for width {width}.");
      EnsureFullPaintGrid(width);
    }
  }
  private readonly ZDO? Zdo;
  private readonly int ExpectedHeightCount;
  private readonly int ExpectedLegacyPaintCount;
  private readonly int ExpectedFullPaintCount;
  private int Operations = 0;
  private Vector3 LastOpPoint = Vector3.zero;
  private float LastOpRadius = 0f;
  private HeightNode[] HeightNodes = [];
  private Color[] PaintNodes = [];
  private bool[] PaintModified = [];
  private byte[] TrailingData = [];

  private struct HeightNode
  {
    public HeightNode()
    {
      LevelDelta = 0f;
      SmoothDelta = 0f;
    }
    public float LevelDelta = 0f;
    public float SmoothDelta = 0f;
  }
  public bool SetHeight(int index, float value)
  {
    if (index < 0 || index >= HeightNodes.Length) return false;
    if (HeightNodes[index].LevelDelta == value && HeightNodes[index].SmoothDelta == 0f)
      return false;
    HeightNodes[index].LevelDelta = value;
    HeightNodes[index].SmoothDelta = 0f;
    return true;
  }
  public void LerpColor(int index, Color color, float multiplier)
  {
    var newColor = Color.Lerp(PaintNodes[index], color, multiplier);
    newColor.a = color.a;
    PaintNodes[index] = newColor;
    PaintModified[index] = newColor != Heightmap.m_paintMaskNothing;
  }
  public bool SetPaint(int index, Color color)
  {
    if (index < 0 || index >= PaintNodes.Length) return false;
    var current = PaintNodes[index];
    if (PaintModified[index] && current.r == color.r && current.g == color.g &&
        current.b == color.b && current.a == color.a) return false;
    PaintNodes[index] = color;
    // A snapshot contains final paint values. Even "nothing" must be explicit
    // so destination biome paint does not leak through the captured result.
    PaintModified[index] = true;
    return true;
  }
  public void MarkOperation(Vector3 position, float radius)
  {
    Operations += 1;
    LastOpPoint = position;
    LastOpRadius = radius;
  }
  private void Load(byte[]? data)
  {
    if (data == null) return;
    ZPackage pkg = new(Utils.Decompress(data));
    var version = pkg.ReadInt();
    if (version != 1)
      throw new InvalidOperationException($"Terrain compiler data version {version} is not supported.");
    Operations = pkg.ReadInt();
    LastOpPoint = pkg.ReadVector3();
    LastOpRadius = pkg.ReadSingle();
    if (!IsFinite(LastOpPoint) || !IsFinite(LastOpRadius))
      throw new InvalidOperationException("Terrain compiler operation metadata is not finite.");
    var heightCount = pkg.ReadInt();
    if (heightCount != ExpectedHeightCount)
      throw new InvalidOperationException($"Terrain height array length {heightCount} does not match {ExpectedHeightCount}.");
    HeightNodes = new HeightNode[heightCount];
    for (int i = 0; i < heightCount; i++)
    {
      var modified = pkg.ReadBool();
      if (!modified) continue;
      var levelDelta = pkg.ReadSingle();
      var smoothDelta = pkg.ReadSingle();
      if (!IsFinite(levelDelta) || !IsFinite(smoothDelta))
        throw new InvalidOperationException("Terrain compiler height data is not finite.");
      HeightNodes[i] = new()
      {
        LevelDelta = levelDelta,
        SmoothDelta = smoothDelta
      };
    }
    var paintCount = pkg.ReadInt();
    if (paintCount != ExpectedLegacyPaintCount && paintCount != ExpectedFullPaintCount)
      throw new InvalidOperationException($"Terrain paint array length {paintCount} is not supported.");
    PaintNodes = new Color[paintCount];
    PaintModified = new bool[paintCount];
    for (int i = 0; i < paintCount; i++)
    {
      PaintNodes[i] = Heightmap.m_paintMaskNothing;
      var modified = pkg.ReadBool();
      PaintModified[i] = modified;
      if (!modified) continue;
      var r = pkg.ReadSingle();
      var g = pkg.ReadSingle();
      var b = pkg.ReadSingle();
      var a = pkg.ReadSingle();
      if (!IsFinite(r) || !IsFinite(g) || !IsFinite(b) || !IsFinite(a))
        throw new InvalidOperationException("Terrain compiler paint data is not finite.");
      PaintNodes[i] = new(r, g, b, a);
    }
    var remaining = pkg.Size() - pkg.GetPos();
    if (remaining < 0)
      throw new InvalidOperationException("Terrain compiler data ended at an invalid position.");
    TrailingData = remaining == 0 ? [] : pkg.ReadByteArray(remaining);
  }
  private void EnsureFullPaintGrid(int width)
  {
    var fullWidth = width + 1;
    var expected = fullWidth * fullWidth;
    if (PaintNodes.Length == expected && PaintModified.Length == expected) return;
    if (PaintNodes.Length != width * width || PaintModified.Length != width * width)
      throw new InvalidOperationException($"Terrain paint array length {PaintNodes.Length} is not supported for width {width}.");

    var oldPaint = PaintNodes;
    var oldModified = PaintModified;
    PaintNodes = new Color[expected];
    PaintModified = new bool[expected];
    for (var z = 0; z < fullWidth; ++z)
    {
      for (var x = 0; x < fullWidth; ++x)
      {
        var sourceX = Mathf.Min(x, width - 1);
        var sourceZ = Mathf.Min(z, width - 1);
        var source = sourceZ * width + sourceX;
        var target = z * fullWidth + x;
        PaintNodes[target] = oldPaint[source];
        PaintModified[target] = oldModified[source];
      }
    }
  }
  public void Save()
  {
    if (Zdo == null) throw new InvalidOperationException("Terrain data has no target ZDO.");
    Save(Zdo);
  }
  public void Save(ZDO zdo)
  {
    zdo.Set(ZDOVars.s_TCData, Serialize());
  }
  public byte[] Serialize()
  {
    ZPackage pkg = new();
    pkg.Write(1);
    pkg.Write(Operations);
    pkg.Write(LastOpPoint);
    pkg.Write(LastOpRadius);
    pkg.Write(HeightNodes.Length);
    foreach (var node in HeightNodes)
    {
      var modified = node.LevelDelta != 0f || node.SmoothDelta != 0f;
      pkg.Write(modified);
      if (!modified) continue;
      pkg.Write(node.LevelDelta);
      pkg.Write(node.SmoothDelta);
    }
    pkg.Write(PaintNodes.Length);
    for (var i = 0; i < PaintNodes.Length; ++i)
    {
      var modified = PaintModified[i];
      pkg.Write(modified);
      if (!modified) continue;
      var node = PaintNodes[i];
      pkg.Write(node.r);
      pkg.Write(node.g);
      pkg.Write(node.b);
      pkg.Write(node.a);
    }
    foreach (var value in TrailingData)
      pkg.Write(value);
    return Utils.Compress(pkg.GetArray());
  }
  private static bool IsFinite(float value) => !float.IsNaN(value) && !float.IsInfinity(value);
  private static bool IsFinite(Vector3 value) => IsFinite(value.x) && IsFinite(value.y) && IsFinite(value.z);
}
